---
- name: set up ssh on windows server
  hosts: windows
  become: true

  tasks:
    - include_vars: "{{ playbook_dir }}/ssh_var.yml"

    - include_role:
        name: win_package_install

    - include_role:
        name: win_service_manage

    - include_role:
        name: win_firewall
