---
- name: update windows firewall ingress
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    protocol: "{{ protocol_name }}"
    direction: in
    action: allow
    state: present
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
