---
- name: install active directory service
  win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: yes
    include_sub_features: yes

- name: configure windows domain
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: ad_reboot

  # this actually waits for node to come back up, so no need for wait_for task
- name: reboot node to complete configuration
  win_reboot:
  when: ad_reboot.reboot_required

- name: verify installation complete
  win_shell: nltest /dclist:{{ ad_domain_name }}
  register: nltest

- debug:
    var: nltest.stdout_lines
