---
- name: install active directory service
  win_feature:
    name: AD-Domain-Services
    state: installed
    include_management_tools: yes
    include_sub_features: yes

- name: configure windows domain
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: ad_reboot

- name: reboot node to complete configuration
  win_reboot:
  when: ad_reboot.reboot_required

- name: wait for reboot to complete
  wait_for:
    port: 5986
    delay: 30
    host: "{{ ansible_ssh_host }}"

- name: verify installation complete
  win_shell: nltest /dclist:{{ ad_domain_name }}
  register: nltest

- debug:
    var: nltest
